### ISSUE TITLE
More asking than a bug.

### ISSUE THREAD

**Issue by Just-another-pleb** [erfanjahanshahlo/node-red-node-lcd#1]
A long time ago when I was starting with RPI, I bought a PiFace CAD board.
It has a 16x2 LCD and a heap of buttons.

It would be nice to use Node-Red to put messages on this display.

Alas that kind of programming - as is - is beyond me.

I saw your node and thought it could solve all my problems.
Alas it doesn't - not your fault - because the LCD on the PiFace CAD board is via the SPI bus I read.

Not wanting to ask too much of you, but I am guessing that this node is not going to work with the set up on that board.

Could you please let me know.
Appreciated.

**Comment by erfanjahanshahlo** [comment]
Hi
Thanks for your information
As you read your text, I wrote a library for red nodes to get started. I live in Iran and the pifacecad board is not sold in this country and I couldn't test the library. If this is not a problem you can try the library and let me know. Thanks
[library link](https://github.com/erfanjahanshahlo/node-red-contrib-pifacecad)
